# Generated by Django 5.1.4 on 2025-01-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mins_studied',
        ),
        migrations.RemoveField(
            model_name='person',
            name='streak_days',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium', max_length=100),
        ),
    ]
